### ISSUE TITLE
Questions about BitOPs

### ISSUE THREAD

**Issue by Ganzhi-e** [Cheeun/CADyQ#6]
Hi, I have some questions about BitOPs!

The paper says BitOPs is measured by generating a 720×1820 picture，so is it Urban100 datasets or others？
I implemented the bitops code myself，The results were the same except for cadyq's. The algorithm for bitops is not in the code，How do you implement BitOPs？ Based on thop or other open source libraries？

Could you please give some explanations?
Thank you very much!

**Comment by Cheeun** [comment]
Hello, sorry for the delayed response!

We calculated the BitOPs using the following equation.
`BitOPs = OPs of unquantized modules + (8.0/32.0) * (FQR/32.0) * OPs of quantized modules`
The OPs of unquantized/quantized modules are measured for a random input for generating a 720p HR image. Also, OPs for the overlapping pixels are included for the patch-wise inference.
Since FQR depends on the input image's content, we use the feature quantization rate (FQR) measured on the Urban100 dataset.
Thanks for your interest in our work!

**Comment by Ganzhi-e** [comment]
Thank you very much for your explanation！
