### ISSUE TITLE
It's a nice work to SR. But I face this problem. For LR_bicubic, the name of pictures have the format of img001x4.png.

### ISSUE THREAD

**Issue by dunanyang** [Cheeun/CADyQ#7]

**Comment by Cheeun** [comment]
Hi, 
Just checking by to see if this issue was solved!
If your DIV2K data is named like img001.png instead of img001x4.png,
you can simply uncomment [L100-101](https://github.com/Cheeun/CADyQ/blob/5ca4344fc241a687b73c5ad977c42c34a52b1ff5/data/srdata.py#L100) and comment [L98-99](https://github.com/Cheeun/CADyQ/blob/5ca4344fc241a687b73c5ad977c42c34a52b1ff5/data/srdata.py#L98C43-L98C43) instead.

`
self.dir_lr, 'X{}/{}{}'.format(s, filename, self.ext[1])
`
